### ISSUE TITLE
macOS App only opens in latest macOS version

### ISSUE THREAD

**Issue by tautropfli** [bash/portal#13]

**Comment by tautropfli** [comment]
I didn't take a screenshot unfortunately.
Maybe @janhohenheim has an idea why this error occurs?

**Comment by janhohenheim** [comment]
Oooh I remember! Guesses:
- Maybe [lipo](https://ss64.com/osx/lipo.html) is at fault?
- Building a universal binary [requires Xcode 12.2](https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary). Is that only available on Monteray?
- Does building with a newer Xcode limit which macOS version can execute the binary?

**Comment by tautropfli** [comment]
<img width="372" alt="image" src="https://user-images.githubusercontent.com/4602612/219116807-6c3ed891-c362-43ba-9a51-ccc8489b8a78.png">

**Comment by tautropfli** [comment]
Fixed in 6b79f986f53009b55401d79ed3318407aa1c1fc0
