### ISSUE TITLE
Make back button more "back-y"

### ISSUE THREAD

**Issue by janhohenheim** [bash/portal#24]
E.g. a back arrow.

**Comment by tautropfli** [comment]
Fixed in 1a3a90b 

<img src="https://user-images.githubusercontent.com/4602612/224507011-ebabd1a9-e538-4bb6-8271-0df023e0a746.png" width="300px" /> <img src="https://user-images.githubusercontent.com/4602612/224507023-00e6730a-41bd-4f99-a51b-4d7cecd328d9.png" width="300px" />
